language: node_js

node_js:
  - stable
  - lts/*

cache:
  yarn: true
  directories:
    - ~/.yarn
    - node_modules

after_script:
  - ./node_modules/coveralls/bin/coveralls.js < coverage/lcov.info
